package model;
// Generated 12/11/2014 11:14:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estampa generated by hbm2java
 */
public class Estampa  implements java.io.Serializable {


     private Integer idEstampa;
     private String nome;
     
    public Estampa() {
    }

	
    public Estampa(String nome) {
        this.nome = nome;
    }

    public Integer getIdEstampa() {
        return this.idEstampa;
    }
    
    public void setIdEstampa(Integer idEstampa) {
        this.idEstampa = idEstampa;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
}


