package model;
// Generated 12/11/2014 11:14:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private Endereco endereco;
     private String nome;
     private String telefone;
     private Set pessoafisicas = new HashSet(0);
     private Set fornecedors = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(Endereco endereco) {
        this.endereco = endereco;
    }
    public Pessoa(Endereco endereco, String nome, String telefone, Set pessoafisicas, Set fornecedors) {
       this.endereco = endereco;
       this.nome = nome;
       this.telefone = telefone;
       this.pessoafisicas = pessoafisicas;
       this.fornecedors = fornecedors;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getPessoafisicas() {
        return this.pessoafisicas;
    }
    
    public void setPessoafisicas(Set pessoafisicas) {
        this.pessoafisicas = pessoafisicas;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }




}


