package model;
// Generated 20/11/2014 14:44:36 by Hibernate Tools 4.3.1



/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private Endereco endereco;
     private String nome;
     private String telefone;


    public Pessoa() {
    }

	
    public Pessoa(Endereco endereco, String nome) {
        this.endereco = endereco;
        this.nome = nome;
    }
    public Pessoa(Endereco endereco, String nome, String telefone) {
       this.endereco = endereco;
       this.nome = nome;
       this.telefone = telefone;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }




}


