package model;
// Generated 12/11/2014 11:14:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tamanho generated by hbm2java
 */
public class Tamanho  implements java.io.Serializable {


     private Integer idTamanho;
     private String nome;

    public Tamanho() {
    }

	
    public Tamanho(String nome) {
        this.nome = nome;
    }
   
    public Integer getIdTamanho() {
        return this.idTamanho;
    }
    
    public void setIdTamanho(Integer idTamanho) {
        this.idTamanho = idTamanho;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
}


