package model;
// Generated 12/11/2014 11:14:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer idVenda;
     private Pessoafisica pessoafisica;
     private Produto produto;
     private Vendedor vendedor;
     private int quantidade;
     private double valor;
     private Date data;

    public Venda() {
    }

    public Venda(Pessoafisica pessoafisica, Produto produto, Vendedor vendedor, int quantidade, double valor, Date data) {
       this.pessoafisica = pessoafisica;
       this.produto = produto;
       this.vendedor = vendedor;
       this.quantidade = quantidade;
       this.valor = valor;
       this.data = data;
    }
   
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }
    public Pessoafisica getPessoafisica() {
        return this.pessoafisica;
    }
    
    public void setPessoafisica(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


