package model;
// Generated 12/11/2014 11:14:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer idVendedor;
     private Pessoafisica pessoafisica;
     private double salario;
     private Date dataAdmissao;
     private Date dataDemissao;
     private Set vendas = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(Pessoafisica pessoafisica, double salario, Date dataAdmissao) {
        this.pessoafisica = pessoafisica;
        this.salario = salario;
        this.dataAdmissao = dataAdmissao;
    }
    public Vendedor(Pessoafisica pessoafisica, double salario, Date dataAdmissao, Date dataDemissao, Set vendas) {
       this.pessoafisica = pessoafisica;
       this.salario = salario;
       this.dataAdmissao = dataAdmissao;
       this.dataDemissao = dataDemissao;
       this.vendas = vendas;
    }
   
    public Integer getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(Integer idVendedor) {
        this.idVendedor = idVendedor;
    }
    public Pessoafisica getPessoafisica() {
        return this.pessoafisica;
    }
    
    public void setPessoafisica(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public Date getDataAdmissao() {
        return this.dataAdmissao;
    }
    
    public void setDataAdmissao(Date dataAdmissao) {
        this.dataAdmissao = dataAdmissao;
    }
    public Date getDataDemissao() {
        return this.dataDemissao;
    }
    
    public void setDataDemissao(Date dataDemissao) {
        this.dataDemissao = dataDemissao;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


