/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.controlPessoa;
import control.controlProduto;
import dao.HibernateUtil;
import dao.daoProduto;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import model.Produto;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.query.JRHibernateQueryExecuterFactory;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Session;

/**
 *
 * @author Paulo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    controlProduto control;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(){
        initComponents();
        setLocationRelativeTo(null);
        this.control = null;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelCadastroProduto = new javax.swing.JLabel();
        jLabelCadastroFornecedor = new javax.swing.JLabel();
        jLabelCadastroVendedor = new javax.swing.JLabel();
        jLabelCadastroCliente = new javax.swing.JLabel();
        jButtonCadastroProduto = new javax.swing.JButton();
        jButtonCadastroFornecedor = new javax.swing.JButton();
        jButtonCadasatroVendedor = new javax.swing.JButton();
        jButtonCadastroCliente = new javax.swing.JButton();
        jPanelListar = new javax.swing.JPanel();
        jLabelListarProduto = new javax.swing.JLabel();
        jLabelListarFornecedor = new javax.swing.JLabel();
        jLabelListarVendedor = new javax.swing.JLabel();
        jLabelListarCliente = new javax.swing.JLabel();
        jButtonListarProduto = new javax.swing.JButton();
        jButtonListarFornecedor = new javax.swing.JButton();
        jButtonListarVendedor = new javax.swing.JButton();
        jButtonListarCliente = new javax.swing.JButton();
        jPanelAtributos = new javax.swing.JPanel();
        jButtonCores = new javax.swing.JButton();
        jButtonEstampa = new javax.swing.JButton();
        jButtonCategoria = new javax.swing.JButton();
        jButtonTamanho = new javax.swing.JButton();
        jPanelVenda = new javax.swing.JPanel();
        jButtonCadastrarVenda = new javax.swing.JButton();
        jButtonListarVenda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jMenuItemCadastroFornecedor = new javax.swing.JMenuItem();
        jMenuItemCadastroVendedor = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCor = new javax.swing.JMenuItem();
        jMenuItemEstampa = new javax.swing.JMenuItem();
        jMenuItemCategoria = new javax.swing.JMenuItem();
        jMenuItemTamanho = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatorioCliente = new javax.swing.JMenuItem();
        jMenuItemRelatorioProduto = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jLabelCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Produto.jpg"))); // NOI18N
        jLabelCadastroProduto.setText("jLabel1");

        jLabelCadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fornecedor.jpg"))); // NOI18N
        jLabelCadastroFornecedor.setText("jLabel1");

        jLabelCadastroVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vendedor.jpg"))); // NOI18N
        jLabelCadastroVendedor.setText("jLabel2");

        jLabelCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cliente.jpg"))); // NOI18N
        jLabelCadastroCliente.setText("jLabel1");

        jButtonCadastroProduto.setText("Produto");
        jButtonCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoActionPerformed(evt);
            }
        });

        jButtonCadastroFornecedor.setText("Fornecedor");
        jButtonCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFornecedorActionPerformed(evt);
            }
        });

        jButtonCadasatroVendedor.setText("Vendedor");
        jButtonCadasatroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadasatroVendedorActionPerformed(evt);
            }
        });

        jButtonCadastroCliente.setText("Cliente");
        jButtonCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jLabelCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabelCadastroVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addComponent(jButtonCadastroProduto)
                .addGap(127, 127, 127)
                .addComponent(jButtonCadastroFornecedor)
                .addGap(137, 137, 137)
                .addComponent(jButtonCadasatroVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jButtonCadastroCliente))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroProduto)
                    .addComponent(jButtonCadastroFornecedor)
                    .addComponent(jButtonCadasatroVendedor)
                    .addComponent(jButtonCadastroCliente))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanelListar.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar"));

        jLabelListarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Produto.jpg"))); // NOI18N
        jLabelListarProduto.setText("jLabel1");

        jLabelListarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fornecedor.jpg"))); // NOI18N
        jLabelListarFornecedor.setText("jLabel1");

        jLabelListarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vendedor.jpg"))); // NOI18N
        jLabelListarVendedor.setText("jLabel2");

        jLabelListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cliente.jpg"))); // NOI18N
        jLabelListarCliente.setText("jLabel1");

        jButtonListarProduto.setText("Produto");
        jButtonListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarProdutoActionPerformed(evt);
            }
        });

        jButtonListarFornecedor.setText("Fornecedor");
        jButtonListarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFornecedorActionPerformed(evt);
            }
        });

        jButtonListarVendedor.setText("Vendedor");
        jButtonListarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarVendedorActionPerformed(evt);
            }
        });

        jButtonListarCliente.setText("Cliente");
        jButtonListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jLabelListarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelListarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(jLabelListarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addComponent(jButtonListarProduto)
                .addGap(126, 126, 126)
                .addComponent(jButtonListarFornecedor)
                .addGap(138, 138, 138)
                .addComponent(jButtonListarVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonListarCliente))
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelListarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarProduto)
                    .addComponent(jButtonListarFornecedor)
                    .addComponent(jButtonListarVendedor)
                    .addComponent(jButtonListarCliente))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jPanelAtributos.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar ou remover\n atributos\n"));

        jButtonCores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cores.jpg"))); // NOI18N
        jButtonCores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoresActionPerformed(evt);
            }
        });

        jButtonEstampa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estampa.jpg"))); // NOI18N
        jButtonEstampa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEstampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstampaActionPerformed(evt);
            }
        });

        jButtonCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.jpg"))); // NOI18N
        jButtonCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jButtonTamanho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tamanho.jpg"))); // NOI18N
        jButtonTamanho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAtributosLayout = new javax.swing.GroupLayout(jPanelAtributos);
        jPanelAtributos.setLayout(jPanelAtributosLayout);
        jPanelAtributosLayout.setHorizontalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jButtonEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(jButtonTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAtributosLayout.setVerticalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelVenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda"));

        jButtonCadastrarVenda.setText("Cadastrar");
        jButtonCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarVendaActionPerformed(evt);
            }
        });

        jButtonListarVenda.setText("Listar");
        jButtonListarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVendaLayout = new javax.swing.GroupLayout(jPanelVenda);
        jPanelVenda.setLayout(jPanelVendaLayout);
        jPanelVendaLayout.setHorizontalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCadastrarVenda)
                .addGap(69, 69, 69)
                .addComponent(jButtonListarVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVendaLayout.setVerticalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarVenda)
                    .addComponent(jButtonListarVenda))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuCadastro.setText("Registrar");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSeparator2);

        jMenuItemCadastroProduto.setText("Produto");
        jMenuItemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroProduto);

        jMenuItemCadastroFornecedor.setText("Fornecedor");
        jMenuItemCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroFornecedor);

        jMenuItemCadastroVendedor.setText("Vendedor");
        jMenuItemCadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroVendedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroVendedor);

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);
        jMenuCadastro.add(jSeparator1);

        jMenuItemCor.setText("Cor");
        jMenuItemCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCor);

        jMenuItemEstampa.setText("Estampa");
        jMenuItemEstampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstampaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemEstampa);

        jMenuItemCategoria.setText("Categoria");
        jMenuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCategoria);

        jMenuItemTamanho.setText("Tamanho");
        jMenuItemTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTamanhoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemTamanho);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelatorioCliente.setText("Cliente");
        jMenuItemRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioClienteActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioCliente);

        jMenuItemRelatorioProduto.setText("Produto");
        jMenuItemRelatorioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioProdutoActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioProduto);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroFornecedorActionPerformed
        // TODO add your handling code here:
        jButtonCadastroFornecedorActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCadastroFornecedorActionPerformed

    private void jButtonCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoActionPerformed
        // TODO add your handling code here:
        TelaCadastroProduto cadastroProduto = new TelaCadastroProduto(this, true);
        cadastroProduto.setLocationRelativeTo(this);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroProdutoActionPerformed

    private void jButtonListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarProdutoActionPerformed
        // TODO add your handling code here:
        TelaPesqProduto pesquisaProduto = new TelaPesqProduto(this, true);
        pesquisaProduto.setLocationRelativeTo(this);
        pesquisaProduto.setDefaultCloseOperation(TelaPrincipal.HIDE_ON_CLOSE);
        pesquisaProduto.setVisible(true);
    }//GEN-LAST:event_jButtonListarProdutoActionPerformed

    private void jButtonCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFornecedorActionPerformed
        // TODO add your handling code here:
        TelaCadastroPessoa cadastroFornecedor;
        try {
            cadastroFornecedor = new TelaCadastroPessoa(this, true);
            cadastroFornecedor.setLocationRelativeTo(this);
            cadastroFornecedor.getjRadioButtonFornecedor().setSelected(true);
            cadastroFornecedor.getjPanelFornecedor().setVisible(true);
            cadastroFornecedor.setDefaultCloseOperation(HIDE_ON_CLOSE);
            cadastroFornecedor.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastroFornecedorActionPerformed

    private void jButtonCadasatroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadasatroVendedorActionPerformed
        // TODO add your handling code here:
        TelaCadastroPessoa cadastroVendedor;
        try {
            cadastroVendedor = new TelaCadastroPessoa(this, true);
            cadastroVendedor.setLocationRelativeTo(this);
            cadastroVendedor.getjRadioButtonVendedor().setSelected(true);
            cadastroVendedor.getjPanelVendedor().setVisible(true);
            cadastroVendedor.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            cadastroVendedor.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonCadasatroVendedorActionPerformed

    private void jButtonCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroPessoa cadastroCliente;
        try {
            cadastroCliente = new TelaCadastroPessoa(this, true);
            cadastroCliente.setLocationRelativeTo(this);
            cadastroCliente.getjRadioButtonCliente().setSelected(true);
            cadastroCliente.getjPanelCliente().setVisible(true);
            cadastroCliente.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            cadastroCliente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastroClienteActionPerformed

    private void jButtonCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoresActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroCor = new TelaCadastrarAtributos(this, true);
        cadastroCor.setLocationRelativeTo(this);
        cadastroCor.getjRadioButtonCor().setSelected(true);
        cadastroCor.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroCor.setVisible(true);
    }//GEN-LAST:event_jButtonCoresActionPerformed

    private void jButtonEstampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstampaActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroEstampa = new TelaCadastrarAtributos(this, true);
        cadastroEstampa.setLocationRelativeTo(this);
        cadastroEstampa.getjRadioButtonEstampa().setSelected(true);
        cadastroEstampa.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroEstampa.setVisible(true);
    }//GEN-LAST:event_jButtonEstampaActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroCategoria = new TelaCadastrarAtributos(this, true);
        cadastroCategoria.setLocationRelativeTo(this);
        cadastroCategoria.getjRadioButtonCategoria().setSelected(true);
        cadastroCategoria.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroCategoria.setVisible(true);
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButtonTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamanhoActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroTamanho = new TelaCadastrarAtributos(this, true);
        cadastroTamanho.setLocationRelativeTo(this);
        cadastroTamanho.getjRadioButtonTamanho().setSelected(true);
        cadastroTamanho.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroTamanho.setVisible(true);
    }//GEN-LAST:event_jButtonTamanhoActionPerformed

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        // TODO add your handling code here:
        jButtonCadastroProdutoActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jMenuItemCadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroVendedorActionPerformed
        // TODO add your handling code here:
        jButtonCadasatroVendedorActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCadastroVendedorActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        jButtonCadastroClienteActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTamanhoActionPerformed
        // TODO add your handling code here:
        jButtonTamanhoActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemTamanhoActionPerformed

    private void jMenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaActionPerformed
        // TODO add your handling code here:
        jButtonCategoriaActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCategoriaActionPerformed

    private void jMenuItemCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCorActionPerformed
        // TODO add your handling code here:
        jButtonCoresActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCorActionPerformed

    private void jMenuItemEstampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstampaActionPerformed
        // TODO add your handling code here:
        jButtonEstampaActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemEstampaActionPerformed

    private void jButtonListarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFornecedorActionPerformed
        // TODO add your handling code here:
        TelaExibirPessoas exibirPessoas;
        try {
            exibirPessoas = new TelaExibirPessoas(this, true);
            exibirPessoas.setLocationRelativeTo(this);
            exibirPessoas.getjRadioButtonFornecedor().setSelected(true);
            exibirPessoas.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            exibirPessoas.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonListarFornecedorActionPerformed

    private void jButtonListarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVendedorActionPerformed
        // TODO add your handling code here:
         TelaExibirPessoas exibirPessoas;
        try {
            exibirPessoas = new TelaExibirPessoas(this, true);
            exibirPessoas.setLocationRelativeTo(this);
            exibirPessoas.getjRadioButtonVendedor().setSelected(true);
            exibirPessoas.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            exibirPessoas.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonListarVendedorActionPerformed

    private void jButtonListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarClienteActionPerformed
        // TODO add your handling code here:
         TelaExibirPessoas exibirPessoas;
        try {
            exibirPessoas = new TelaExibirPessoas(this, true);
            exibirPessoas.setLocationRelativeTo(this);
            exibirPessoas.getjRadioButtonCliente().setSelected(true);
            exibirPessoas.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            exibirPessoas.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonListarClienteActionPerformed

    private void jButtonCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVendaActionPerformed
        // TODO add your handling code here:
        TelaVenda cadastroVenda;
        try {
            cadastroVenda = new TelaVenda(this, true);
            cadastroVenda.setLocationRelativeTo(this);
            cadastroVenda.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonCadastrarVendaActionPerformed

    private void jButtonListarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVendaActionPerformed
        // TODO add your handling code here:
        TelaPesqVenda telaVenda = new TelaPesqVenda(this, true);
        telaVenda.setLocationRelativeTo(this);
        telaVenda.setVisible(true);
    }//GEN-LAST:event_jButtonListarVendaActionPerformed

    private void jMenuItemRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioClienteActionPerformed
        // TODO add your handling code here:
  
            
            // PASSO 1 - Caminho do relatório
            InputStream rel = getClass().getResourceAsStream("../report/Cliente.jasper");

            // PASSO 2 - Criar parâmetros de Pesquisa 
            Map parametros = new HashMap();
            parametros.put("SUBREPORT_DIR", "src/report/");

            // PASSO 3 - Carregar o relatório com os dados
            JasperPrint print = null;
        try {
            // Passar o caminho do RELATORIO e os PARAMETROS dos PASSSOS 1 e 2 e os DADOS
            print = JasperFillManager.fillReport(rel, parametros);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


            // PASSO 4 - Mostrat em uma JANELA
            JasperViewer janela = new JasperViewer(print, false);
            janela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioClienteActionPerformed

    private void jMenuItemRelatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioProdutoActionPerformed
        // TODO add your handling code here:
         Session sessao = null;
        try {
            sessao = HibernateUtil.getSessionFactory().openSession();
            daoProduto dao = new daoProduto();
            List<Produto> lista = dao.getNome("");
            
            // Dados para o RELATORIO
            JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(lista);
            
            // PASSO 1 - Caminho do relatório
            InputStream rel = getClass().getResourceAsStream("../report/RelatorioProduto.jasper");

            // PASSO 2 - Criar parâmetros de Pesquisa 
            Map parametros = new HashMap();
            //parametros.put( "src/report/");

            // PASSO 3 - Carregar o relatório com os dados
            JasperPrint print;
            // Passar o caminho do RELATORIO e os PARAMETROS dos PASSSOS 1 e 2 e os DADOS
            print = JasperFillManager.fillReport(rel, parametros, dados);


            // PASSO 4 - Mostrat em uma JANELA
            JasperViewer janela = new JasperViewer(print, false);
            janela.setVisible(true);
            
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jMenuItemRelatorioProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadasatroVendedor;
    private javax.swing.JButton jButtonCadastrarVenda;
    private javax.swing.JButton jButtonCadastroCliente;
    private javax.swing.JButton jButtonCadastroFornecedor;
    private javax.swing.JButton jButtonCadastroProduto;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonCores;
    private javax.swing.JButton jButtonEstampa;
    private javax.swing.JButton jButtonListarCliente;
    private javax.swing.JButton jButtonListarFornecedor;
    private javax.swing.JButton jButtonListarProduto;
    private javax.swing.JButton jButtonListarVenda;
    private javax.swing.JButton jButtonListarVendedor;
    private javax.swing.JButton jButtonTamanho;
    private javax.swing.JLabel jLabelCadastroCliente;
    private javax.swing.JLabel jLabelCadastroFornecedor;
    private javax.swing.JLabel jLabelCadastroProduto;
    private javax.swing.JLabel jLabelCadastroVendedor;
    private javax.swing.JLabel jLabelListarCliente;
    private javax.swing.JLabel jLabelListarFornecedor;
    private javax.swing.JLabel jLabelListarProduto;
    private javax.swing.JLabel jLabelListarVendedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCadastroFornecedor;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemCadastroVendedor;
    private javax.swing.JMenuItem jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemCor;
    private javax.swing.JMenuItem jMenuItemEstampa;
    private javax.swing.JMenuItem jMenuItemRelatorioCliente;
    private javax.swing.JMenuItem jMenuItemRelatorioProduto;
    private javax.swing.JMenuItem jMenuItemTamanho;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAtributos;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JPanel jPanelVenda;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
