/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.controlAtributos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Matheus Claudino
 */
public class TelaCadastrarAtributos extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastrarAtributos
     */
    controlAtributos controlAtri;

    public TelaCadastrarAtributos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controlAtri = new controlAtributos();
    }

    public JRadioButton getjRadioButtonCategoria() {
        return jRadioButtonCategoria;
    }

    public void setjRadioButtonCategoria(JRadioButton jRadioButtonCategoria) {
        this.jRadioButtonCategoria = jRadioButtonCategoria;
    }

    public JRadioButton getjRadioButtonCor() {
        return jRadioButtonCor;
    }

    public void setjRadioButtonCor(JRadioButton jRadioButtonCor) {
        this.jRadioButtonCor = jRadioButtonCor;
    }

    public JRadioButton getjRadioButtonEstampa() {
        return jRadioButtonEstampa;
    }

    public void setjRadioButtonEstampa(JRadioButton jRadioButtonEstampa) {
        this.jRadioButtonEstampa = jRadioButtonEstampa;
    }

    public JRadioButton getjRadioButtonTamanho() {
        return jRadioButtonTamanho;
    }

    public void setjRadioButtonTamanho(JRadioButton jRadioButtonTamanho) {
        this.jRadioButtonTamanho = jRadioButtonTamanho;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoAtributo = new javax.swing.ButtonGroup();
        jPanelAtributos = new javax.swing.JPanel();
        jPanelTipoAtributo = new javax.swing.JPanel();
        jRadioButtonCor = new javax.swing.JRadioButton();
        jRadioButtonEstampa = new javax.swing.JRadioButton();
        jRadioButtonCategoria = new javax.swing.JRadioButton();
        jRadioButtonTamanho = new javax.swing.JRadioButton();
        jPanelInformacao = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();

        setTitle("Cadastrar Atributo");

        jPanelAtributos.setBackground(new java.awt.Color(11, 122, 150));

        jPanelTipoAtributo.setBackground(new java.awt.Color(11, 122, 150));
        jPanelTipoAtributo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO ATRIBUTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelTipoAtributo.setToolTipText("");

        buttonGroupTipoAtributo.add(jRadioButtonCor);
        jRadioButtonCor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonCor.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCor.setMnemonic('1');
        jRadioButtonCor.setText("Cor");
        jRadioButtonCor.setContentAreaFilled(false);

        buttonGroupTipoAtributo.add(jRadioButtonEstampa);
        jRadioButtonEstampa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonEstampa.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEstampa.setMnemonic('2');
        jRadioButtonEstampa.setText("Estampa");
        jRadioButtonEstampa.setContentAreaFilled(false);

        buttonGroupTipoAtributo.add(jRadioButtonCategoria);
        jRadioButtonCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCategoria.setMnemonic('3');
        jRadioButtonCategoria.setText("Categoria");
        jRadioButtonCategoria.setContentAreaFilled(false);

        buttonGroupTipoAtributo.add(jRadioButtonTamanho);
        jRadioButtonTamanho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonTamanho.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTamanho.setMnemonic('4');
        jRadioButtonTamanho.setText("Tamanho");
        jRadioButtonTamanho.setToolTipText("");
        jRadioButtonTamanho.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanelTipoAtributoLayout = new javax.swing.GroupLayout(jPanelTipoAtributo);
        jPanelTipoAtributo.setLayout(jPanelTipoAtributoLayout);
        jPanelTipoAtributoLayout.setHorizontalGroup(
            jPanelTipoAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoAtributoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonEstampa)
                .addGap(26, 26, 26)
                .addComponent(jRadioButtonCategoria)
                .addGap(30, 30, 30)
                .addComponent(jRadioButtonTamanho)
                .addGap(19, 19, 19))
        );
        jPanelTipoAtributoLayout.setVerticalGroup(
            jPanelTipoAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoAtributoLayout.createSequentialGroup()
                .addGroup(jPanelTipoAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCor)
                    .addComponent(jRadioButtonEstampa)
                    .addComponent(jRadioButtonCategoria)
                    .addComponent(jRadioButtonTamanho))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanelInformacao.setBackground(new java.awt.Color(11, 122, 150));
        jPanelInformacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMAÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");

        javax.swing.GroupLayout jPanelInformacaoLayout = new javax.swing.GroupLayout(jPanelInformacao);
        jPanelInformacao.setLayout(jPanelInformacaoLayout);
        jPanelInformacaoLayout.setHorizontalGroup(
            jPanelInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInformacaoLayout.setVerticalGroup(
            jPanelInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacaoLayout.createSequentialGroup()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAtributosLayout = new javax.swing.GroupLayout(jPanelAtributos);
        jPanelAtributos.setLayout(jPanelAtributosLayout);
        jPanelAtributosLayout.setHorizontalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTipoAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addComponent(jPanelInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButtonCadastrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAtributosLayout.setVerticalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTipoAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonCadastrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelAtributos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        int id;
        if (jTextFieldNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "PREENCHA O CAMPO NOME!");
        } else {
            id = controlAtri.inserirAtributo(
                    buttonGroupTipoAtributo.getSelection().getMnemonic(),
                    jTextFieldNome.getText()
            );
            JOptionPane.showMessageDialog(this, "Atributo Cadastrado!");
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtributos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastrarAtributos dialog;
                try {
                    dialog = new TelaCadastrarAtributos(new javax.swing.JFrame(), true);

                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaCadastrarAtributos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoAtributo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelAtributos;
    private javax.swing.JPanel jPanelInformacao;
    private javax.swing.JPanel jPanelTipoAtributo;
    private javax.swing.JRadioButton jRadioButtonCategoria;
    private javax.swing.JRadioButton jRadioButtonCor;
    private javax.swing.JRadioButton jRadioButtonEstampa;
    private javax.swing.JRadioButton jRadioButtonTamanho;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
