/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.controlPessoa;
import control.controlProduto;
import dao.daoPessoa;
import dao.HibernateUtil;
import dao.daoProduto;
import dao.daoVenda;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.InputStream;
import java.net.URL;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.UnsupportedLookAndFeelException;
import model.Pessoa;
import model.Produto;
import model.Venda;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.query.JRHibernateQueryExecuterFactory;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Session;

/**
 *
 * @author Paulo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    controlProduto control;
    daoPessoa bancoPessoa;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() throws SQLException, Exception {
        initComponents();
        setLocationRelativeTo(null);
        this.control = null;
        bancoPessoa = new daoPessoa();
        this.setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelCadastroProduto = new javax.swing.JLabel();
        jLabelCadastroFornecedor = new javax.swing.JLabel();
        jLabelCadastroVendedor = new javax.swing.JLabel();
        jLabelCadastroCliente = new javax.swing.JLabel();
        jButtonCadastroProduto = new javax.swing.JButton();
        jButtonCadastroFornecedor = new javax.swing.JButton();
        jButtonCadasatroVendedor = new javax.swing.JButton();
        jButtonCadastroCliente = new javax.swing.JButton();
        jPanelListar = new javax.swing.JPanel();
        jLabelListarProduto = new javax.swing.JLabel();
        jLabelListarFornecedor = new javax.swing.JLabel();
        jLabelListarVendedor = new javax.swing.JLabel();
        jLabelListarCliente = new javax.swing.JLabel();
        jButtonListarProduto = new javax.swing.JButton();
        jButtonListarFornecedor = new javax.swing.JButton();
        jButtonListarVendedor = new javax.swing.JButton();
        jButtonListarCliente = new javax.swing.JButton();
        jPanelAtributos = new javax.swing.JPanel();
        jButtonCores = new javax.swing.JButton();
        jButtonEstampa = new javax.swing.JButton();
        jButtonCategoria = new javax.swing.JButton();
        jButtonTamanho = new javax.swing.JButton();
        jPanelVenda = new javax.swing.JPanel();
        jButtonCadastrarVenda = new javax.swing.JButton();
        jButtonListarVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        jMenuItemCadastroFornecedor = new javax.swing.JMenuItem();
        jMenuItemCadastroVendedor = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCor = new javax.swing.JMenuItem();
        jMenuItemEstampa = new javax.swing.JMenuItem();
        jMenuItemCategoria = new javax.swing.JMenuItem();
        jMenuItemTamanho = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatorioCliente = new javax.swing.JMenuItem();
        jMenuItemRelatorioVendedor = new javax.swing.JMenuItem();
        jMenuItemRelatorioFornecedor = new javax.swing.JMenuItem();
        jMenuItemRelatorioProduto = new javax.swing.JMenuItem();
        jMenuItemRelatorioVenda = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(11, 122, 150));

        jPanelCadastro.setBackground(new java.awt.Color(11, 122, 150));
        jPanelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelCadastro.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clothe-flat-128px-plus.png"))); // NOI18N

        jLabelCadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fornecedor-flat-128px-plus.png"))); // NOI18N

        jLabelCadastroVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor-flat-128px-plus.png"))); // NOI18N

        jLabelCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente-flat-128px-plus.png"))); // NOI18N

        jButtonCadastroProduto.setText("Produto");
        jButtonCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoActionPerformed(evt);
            }
        });

        jButtonCadastroFornecedor.setText("Fornecedor");
        jButtonCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFornecedorActionPerformed(evt);
            }
        });

        jButtonCadasatroVendedor.setText("Vendedor");
        jButtonCadasatroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadasatroVendedorActionPerformed(evt);
            }
        });

        jButtonCadastroCliente.setText("Cliente");
        jButtonCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonCadastroProduto)
                        .addGap(101, 101, 101)
                        .addComponent(jButtonCadastroFornecedor))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtonCadasatroVendedor)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCadastroVendedor)
                        .addGap(13, 13, 13)))
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonCadastroCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCadastroCliente)
                        .addGap(61, 61, 61))))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelCadastroVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroProduto)
                    .addComponent(jButtonCadastroFornecedor)
                    .addComponent(jButtonCadasatroVendedor)))
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastroCliente))
        );

        jPanelListar.setBackground(new java.awt.Color(11, 122, 150));
        jPanelListar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelListarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clothe-flat-128px-search.png"))); // NOI18N

        jLabelListarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fornecedor-flat-128px-search.png"))); // NOI18N

        jLabelListarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor-flat-128px-search.png"))); // NOI18N

        jLabelListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente-flat-128px-search.png"))); // NOI18N
        jLabelListarCliente.setText("jLabel1");

        jButtonListarProduto.setText("Produto");
        jButtonListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarProdutoActionPerformed(evt);
            }
        });

        jButtonListarFornecedor.setText("Fornecedor");
        jButtonListarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFornecedorActionPerformed(evt);
            }
        });

        jButtonListarVendedor.setText("Vendedor");
        jButtonListarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarVendedorActionPerformed(evt);
            }
        });

        jButtonListarCliente.setText("Cliente");
        jButtonListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarLayout.createSequentialGroup()
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabelListarFornecedor))
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButtonListarProduto)
                        .addGap(103, 103, 103)
                        .addComponent(jButtonListarFornecedor)))
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListarVendedor)
                        .addGap(109, 109, 109)
                        .addComponent(jButtonListarCliente))
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabelListarVendedor)
                        .addGap(59, 59, 59)
                        .addComponent(jLabelListarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelListarCliente)
                            .addComponent(jLabelListarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonListarCliente)
                            .addComponent(jButtonListarVendedor)))
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelListarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonListarProduto)
                            .addComponent(jButtonListarFornecedor))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelAtributos.setBackground(new java.awt.Color(11, 122, 150));
        jPanelAtributos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADICIONAR OU REMOVER ATRIBUTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jButtonCores.setBackground(new java.awt.Color(11, 122, 150));
        jButtonCores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cor.png"))); // NOI18N
        jButtonCores.setContentAreaFilled(false);
        jButtonCores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoresActionPerformed(evt);
            }
        });

        jButtonEstampa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estampa.png"))); // NOI18N
        jButtonEstampa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEstampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstampaActionPerformed(evt);
            }
        });

        jButtonCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.jpg"))); // NOI18N
        jButtonCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jButtonTamanho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tamanho.jpg"))); // NOI18N
        jButtonTamanho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAtributosLayout = new javax.swing.GroupLayout(jPanelAtributos);
        jPanelAtributos.setLayout(jPanelAtributosLayout);
        jPanelAtributosLayout.setHorizontalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCores, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButtonEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(jButtonTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAtributosLayout.setVerticalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addComponent(jButtonCores, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEstampa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelVenda.setBackground(new java.awt.Color(11, 122, 150));
        jPanelVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jButtonCadastrarVenda.setText("Cadastrar");
        jButtonCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarVendaActionPerformed(evt);
            }
        });

        jButtonListarVenda.setText("Listar");
        jButtonListarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarVendaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venda-plus.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venda-search.png"))); // NOI18N

        javax.swing.GroupLayout jPanelVendaLayout = new javax.swing.GroupLayout(jPanelVenda);
        jPanelVenda.setLayout(jPanelVendaLayout);
        jPanelVendaLayout.setHorizontalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonCadastrarVenda)))
                .addGap(51, 51, 51)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonListarVenda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVendaLayout.setVerticalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarVenda)
                    .addComponent(jButtonListarVenda)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuCadastro.setText("Registrar");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jSeparator2);

        jMenuItemCadastroProduto.setText("Produto");
        jMenuItemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroProduto);

        jMenuItemCadastroFornecedor.setText("Fornecedor");
        jMenuItemCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroFornecedor);

        jMenuItemCadastroVendedor.setText("Vendedor");
        jMenuItemCadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroVendedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroVendedor);

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);
        jMenuCadastro.add(jSeparator1);

        jMenuItemCor.setText("Cor");
        jMenuItemCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCor);

        jMenuItemEstampa.setText("Estampa");
        jMenuItemEstampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstampaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemEstampa);

        jMenuItemCategoria.setText("Categoria");
        jMenuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCategoria);

        jMenuItemTamanho.setText("Tamanho");
        jMenuItemTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTamanhoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemTamanho);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelatorioCliente.setText("Clientes");
        jMenuItemRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioClienteActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioCliente);

        jMenuItemRelatorioVendedor.setText("Vendedores(as)");
        jMenuItemRelatorioVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioVendedorActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioVendedor);

        jMenuItemRelatorioFornecedor.setText("Fornecedores");
        jMenuItemRelatorioFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioFornecedorActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioFornecedor);

        jMenuItemRelatorioProduto.setText("Produto");
        jMenuItemRelatorioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioProdutoActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioProduto);

        jMenuItemRelatorioVenda.setText("Venda");
        jMenuItemRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioVendaActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorioVenda);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroFornecedorActionPerformed
        // TODO add your handling code here:
        jButtonCadastroFornecedorActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCadastroFornecedorActionPerformed

    private void jButtonCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoActionPerformed
        // TODO add your handling code here:
        TelaCadastroProduto cadastroProduto = new TelaCadastroProduto(this, true);
        cadastroProduto.setLocationRelativeTo(this);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroProdutoActionPerformed

    private void jButtonListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarProdutoActionPerformed
        // TODO add your handling code here:
        TelaPesqProduto pesquisaProduto = new TelaPesqProduto(this, true);
        pesquisaProduto.setLocationRelativeTo(this);
        pesquisaProduto.setDefaultCloseOperation(TelaPrincipal.HIDE_ON_CLOSE);
        pesquisaProduto.setVisible(true);
    }//GEN-LAST:event_jButtonListarProdutoActionPerformed

    private void jButtonCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFornecedorActionPerformed
        // TODO add your handling code here:
        TelaCadastroPessoa cadastroFornecedor;
        try {
            cadastroFornecedor = new TelaCadastroPessoa(this, true);
            cadastroFornecedor.setLocationRelativeTo(this);
            cadastroFornecedor.getjRadioButtonFornecedor().setSelected(true);
            cadastroFornecedor.getjPanelFornecedor().setVisible(true);
            cadastroFornecedor.setDefaultCloseOperation(HIDE_ON_CLOSE);
            cadastroFornecedor.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastroFornecedorActionPerformed

    private void jButtonCadasatroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadasatroVendedorActionPerformed
        // TODO add your handling code here:
        TelaCadastroPessoa cadastroVendedor;
        try {
            cadastroVendedor = new TelaCadastroPessoa(this, true);
            cadastroVendedor.setLocationRelativeTo(this);
            cadastroVendedor.getjRadioButtonVendedor().setSelected(true);
            cadastroVendedor.getjPanelVendedor().setVisible(true);
            cadastroVendedor.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            cadastroVendedor.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonCadasatroVendedorActionPerformed

    private void jButtonCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroPessoa cadastroCliente;
        try {
            cadastroCliente = new TelaCadastroPessoa(this, true);
            cadastroCliente.setLocationRelativeTo(this);
            cadastroCliente.getjRadioButtonCliente().setSelected(true);
            cadastroCliente.getjPanelCliente().setVisible(true);
            cadastroCliente.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            cadastroCliente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastroClienteActionPerformed

    private void jButtonCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoresActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroCor = new TelaCadastrarAtributos(this, true);
        cadastroCor.setLocationRelativeTo(this);
        cadastroCor.getjRadioButtonCor().setSelected(true);
        cadastroCor.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroCor.setVisible(true);
    }//GEN-LAST:event_jButtonCoresActionPerformed

    private void jButtonEstampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstampaActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroEstampa = new TelaCadastrarAtributos(this, true);
        cadastroEstampa.setLocationRelativeTo(this);
        cadastroEstampa.getjRadioButtonEstampa().setSelected(true);
        cadastroEstampa.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroEstampa.setVisible(true);
    }//GEN-LAST:event_jButtonEstampaActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroCategoria = new TelaCadastrarAtributos(this, true);
        cadastroCategoria.setLocationRelativeTo(this);
        cadastroCategoria.getjRadioButtonCategoria().setSelected(true);
        cadastroCategoria.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroCategoria.setVisible(true);
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButtonTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamanhoActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAtributos cadastroTamanho = new TelaCadastrarAtributos(this, true);
        cadastroTamanho.setLocationRelativeTo(this);
        cadastroTamanho.getjRadioButtonTamanho().setSelected(true);
        cadastroTamanho.setDefaultCloseOperation(TelaCadastrarAtributos.HIDE_ON_CLOSE);
        cadastroTamanho.setVisible(true);
    }//GEN-LAST:event_jButtonTamanhoActionPerformed

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        // TODO add your handling code here:
        jButtonCadastroProdutoActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jMenuItemCadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroVendedorActionPerformed
        // TODO add your handling code here:
        jButtonCadasatroVendedorActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCadastroVendedorActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        jButtonCadastroClienteActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTamanhoActionPerformed
        // TODO add your handling code here:
        jButtonTamanhoActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemTamanhoActionPerformed

    private void jMenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaActionPerformed
        // TODO add your handling code here:
        jButtonCategoriaActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCategoriaActionPerformed

    private void jMenuItemCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCorActionPerformed
        // TODO add your handling code here:
        jButtonCoresActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemCorActionPerformed

    private void jMenuItemEstampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstampaActionPerformed
        // TODO add your handling code here:
        jButtonEstampaActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemEstampaActionPerformed

    private void jButtonListarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFornecedorActionPerformed
        // TODO add your handling code here:
        TelaExibirPessoas exibirPessoas;
        try {
            exibirPessoas = new TelaExibirPessoas(this, true);
            exibirPessoas.setLocationRelativeTo(this);
            exibirPessoas.getjRadioButtonFornecedor().setSelected(true);
            exibirPessoas.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            exibirPessoas.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonListarFornecedorActionPerformed

    private void jButtonListarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVendedorActionPerformed
        // TODO add your handling code here:
        TelaExibirPessoas exibirPessoas;
        try {
            exibirPessoas = new TelaExibirPessoas(this, true);
            exibirPessoas.setLocationRelativeTo(this);
            exibirPessoas.getjRadioButtonVendedor().setSelected(true);
            exibirPessoas.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            exibirPessoas.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonListarVendedorActionPerformed

    private void jButtonListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarClienteActionPerformed
        // TODO add your handling code here:
        TelaExibirPessoas exibirPessoas;
        try {
            exibirPessoas = new TelaExibirPessoas(this, true);
            exibirPessoas.setLocationRelativeTo(this);
            exibirPessoas.getjRadioButtonCliente().setSelected(true);
            exibirPessoas.setDefaultCloseOperation(TelaCadastroPessoa.HIDE_ON_CLOSE);
            exibirPessoas.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonListarClienteActionPerformed

    private void jButtonCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVendaActionPerformed
        // TODO add your handling code here:
        TelaVenda cadastroVenda;
        try {
            cadastroVenda = new TelaVenda(this, true);
            cadastroVenda.setLocationRelativeTo(this);
            cadastroVenda.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonCadastrarVendaActionPerformed

    private void jButtonListarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVendaActionPerformed
        // TODO add your handling code here:
        TelaPesqVenda telaVenda = new TelaPesqVenda(this, true);
        telaVenda.setLocationRelativeTo(this);
        telaVenda.setVisible(true);
    }//GEN-LAST:event_jButtonListarVendaActionPerformed

    private void jMenuItemRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioClienteActionPerformed
        // TODO add your handling code here:

        List<Pessoa> lista = bancoPessoa.consultaPessoa('C');

        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(lista);

        InputStream rel = getClass().getResourceAsStream("../report/Cliente.jasper");

        Map parametros = new HashMap();

        parametros.put(JRHibernateQueryExecuterFactory.PARAMETER_HIBERNATE_SESSION,
                dao.HibernateUtil.getSessionFactory().openSession());

        JasperPrint print = null;

        try {
            print = JasperFillManager.fillReport(rel, parametros, dados);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        JasperViewer janela = new JasperViewer(print, false);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioClienteActionPerformed

   
    private void jMenuItemRelatorioVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioVendedorActionPerformed
        // TODO add your handling code here:
        List<Pessoa> lista = bancoPessoa.consultaPessoa('V');

        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(lista);

        InputStream rel = getClass().getResourceAsStream("../report/Vendedor.jasper");

        Map parametros = new HashMap();

        parametros.put(JRHibernateQueryExecuterFactory.PARAMETER_HIBERNATE_SESSION,
                dao.HibernateUtil.getSessionFactory().openSession());

        JasperPrint print = null;

        try {
            print = JasperFillManager.fillReport(rel, parametros, dados);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        JasperViewer janela = new JasperViewer(print, false);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioVendedorActionPerformed

    private void jMenuItemRelatorioFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioFornecedorActionPerformed
        // TODO add your handling code here:
        List<Pessoa> lista = bancoPessoa.consultaPessoa('F');

        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(lista);

        InputStream rel = getClass().getResourceAsStream("../report/Fornecedor.jasper");

        Map parametros = new HashMap();

        parametros.put(JRHibernateQueryExecuterFactory.PARAMETER_HIBERNATE_SESSION,
                dao.HibernateUtil.getSessionFactory().openSession());

        JasperPrint print = null;

        try {
            print = JasperFillManager.fillReport(rel, parametros, dados);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        JasperViewer janela = new JasperViewer(print, false);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioFornecedorActionPerformed
   
    private void jMenuItemRelatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioProdutoActionPerformed
        // TODO add your handling code here:
        try {
            daoProduto dao = new daoProduto();
            List<Produto> lista = dao.getNome("");

            // Dados para o RELATORIO
            JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(lista);

            // PASSO 1 - Caminho do relatório
            InputStream rel = getClass().getResourceAsStream("../report/RelatorioProduto.jasper");

            // PASSO 2 - Criar parâmetros de Pesquisa 
            Map parametros = new HashMap();

            // PASSO 3 - Carregar o relatório com os dados
            // Passar o caminho do RELATORIO e os PARAMETROS dos PASSSOS 1 e 2 e os DADOS
            JasperPrint print;
            print = JasperFillManager.fillReport(rel, parametros, dados);

            // PASSO 4 - Mostrar em uma JANELA
            JasperViewer janela = new JasperViewer(print, false);
            janela.setVisible(true);

        } catch (Exception e) {

        }

    }//GEN-LAST:event_jMenuItemRelatorioProdutoActionPerformed

    private void jMenuItemRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioVendaActionPerformed
        // TODO add your handling code here:
        try {
            daoVenda dao = new daoVenda();
            List<Venda> lista = dao.getVenda();

            // Dados para o RELATORIO
            JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(lista);

            // PASSO 1 - Caminho do relatório
            InputStream rel = getClass().getResourceAsStream("../report/RelatorioVenda.jasper");

            // PASSO 2 - Criar parâmetros de Pesquisa 
            Map parametros = new HashMap();

            // PASSO 3 - Carregar o relatório com os dados
            // Passar o caminho do RELATORIO e os PARAMETROS dos PASSSOS 1 e 2 e os DADOS
            JasperPrint print;

            print = JasperFillManager.fillReport(rel, parametros, dados);

            // PASSO 4 - Mostrar em uma JANELA
            JasperViewer janela = new JasperViewer(print, false);
            janela.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItemRelatorioVendaActionPerformed
    
    /**
             * @param args the command line arguments
             */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                // JOptionPane.showMessageDialog(null, info.getName() );
                if ("Windows".equals(info.getName())) {
                    
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
            } catch (ClassNotFoundException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }
    public void setIcon() {
        URL url = this.getClass().getResource("/img/icon-sale-border-64.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadasatroVendedor;
    private javax.swing.JButton jButtonCadastrarVenda;
    private javax.swing.JButton jButtonCadastroCliente;
    private javax.swing.JButton jButtonCadastroFornecedor;
    private javax.swing.JButton jButtonCadastroProduto;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonCores;
    private javax.swing.JButton jButtonEstampa;
    private javax.swing.JButton jButtonListarCliente;
    private javax.swing.JButton jButtonListarFornecedor;
    private javax.swing.JButton jButtonListarProduto;
    private javax.swing.JButton jButtonListarVenda;
    private javax.swing.JButton jButtonListarVendedor;
    private javax.swing.JButton jButtonTamanho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCadastroCliente;
    private javax.swing.JLabel jLabelCadastroFornecedor;
    private javax.swing.JLabel jLabelCadastroProduto;
    private javax.swing.JLabel jLabelCadastroVendedor;
    private javax.swing.JLabel jLabelListarCliente;
    private javax.swing.JLabel jLabelListarFornecedor;
    private javax.swing.JLabel jLabelListarProduto;
    private javax.swing.JLabel jLabelListarVendedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCadastroFornecedor;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemCadastroVendedor;
    private javax.swing.JMenuItem jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemCor;
    private javax.swing.JMenuItem jMenuItemEstampa;
    private javax.swing.JMenuItem jMenuItemRelatorioCliente;
    private javax.swing.JMenuItem jMenuItemRelatorioFornecedor;
    private javax.swing.JMenuItem jMenuItemRelatorioProduto;
    private javax.swing.JMenuItem jMenuItemRelatorioVenda;
    private javax.swing.JMenuItem jMenuItemRelatorioVendedor;
    private javax.swing.JMenuItem jMenuItemTamanho;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAtributos;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JPanel jPanelVenda;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
