/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.controlPessoa;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.Pessoa;

/**
 *
 * @author Paulo
 */
public class TelaExibirPessoas extends javax.swing.JDialog {

    /**
     * Creates new form TelaExibirPessoas
     */
    controlPessoa controladoraPessoa;
    Pessoa pesSelecionado;
    TelaCadastroPessoa telaCadastroPessoa;
    
      public TelaCadastroPessoa getTela() {
        return this.telaCadastroPessoa;
    }
    
    public TelaExibirPessoas(java.awt.Frame parent, boolean modal) throws SQLException, Exception {
        super(parent, modal);
        initComponents();
        controladoraPessoa = new controlPessoa();
        pesSelecionado = null;
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanelExibirPessoas = new javax.swing.JPanel();
        jPanelTabelaPessoas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePessoas = new javax.swing.JTable();
        jPanelTipo = new javax.swing.JPanel();
        jRadioButtonVendedores = new javax.swing.JRadioButton();
        jRadioButtonClientes = new javax.swing.JRadioButton();
        jRadioButtonFornecedores = new javax.swing.JRadioButton();
        jButtonSelecionar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelTabelaPessoas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listagem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTablePessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF/CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePessoas.getTableHeader().setResizingAllowed(false);
        jTablePessoas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTablePessoas);

        javax.swing.GroupLayout jPanelTabelaPessoasLayout = new javax.swing.GroupLayout(jPanelTabelaPessoas);
        jPanelTabelaPessoas.setLayout(jPanelTabelaPessoasLayout);
        jPanelTabelaPessoasLayout.setHorizontalGroup(
            jPanelTabelaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTabelaPessoasLayout.setVerticalGroup(
            jPanelTabelaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo\n"));

        buttonGroupTipo.add(jRadioButtonVendedores);
        jRadioButtonVendedores.setMnemonic('V');
        jRadioButtonVendedores.setText("Vendedores");
        jRadioButtonVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVendedoresActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonClientes);
        jRadioButtonClientes.setMnemonic('C');
        jRadioButtonClientes.setText("Clientes");
        jRadioButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClientesActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonFornecedores);
        jRadioButtonFornecedores.setMnemonic('F');
        jRadioButtonFornecedores.setText("Fornecedores");
        jRadioButtonFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoLayout = new javax.swing.GroupLayout(jPanelTipo);
        jPanelTipo.setLayout(jPanelTipoLayout);
        jPanelTipoLayout.setHorizontalGroup(
            jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButtonVendedores)
            .addComponent(jRadioButtonClientes)
            .addComponent(jRadioButtonFornecedores)
        );
        jPanelTipoLayout.setVerticalGroup(
            jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonVendedores)
                .addGap(9, 9, 9)
                .addComponent(jRadioButtonClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonFornecedores)
                .addContainerGap())
        );

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelExibirPessoasLayout = new javax.swing.GroupLayout(jPanelExibirPessoas);
        jPanelExibirPessoas.setLayout(jPanelExibirPessoasLayout);
        jPanelExibirPessoasLayout.setHorizontalGroup(
            jPanelExibirPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExibirPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExibirPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecionar))
                .addGroup(jPanelExibirPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelExibirPessoasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTabelaPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelExibirPessoasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonCancelar)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelExibirPessoasLayout.setVerticalGroup(
            jPanelExibirPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExibirPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExibirPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTabelaPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelExibirPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelecionar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelExibirPessoas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelExibirPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
       public JRadioButton getjRadioButtonCliente() {
        return jRadioButtonClientes;
    }

    public void setjRadioButtonCliente(JRadioButton jRadioButtonCliente) {
        this.jRadioButtonClientes = jRadioButtonCliente;
    }

    public JRadioButton getjRadioButtonFornecedor() {
        return jRadioButtonFornecedores;
    }

    public void setjRadioButtonFornecedor(JRadioButton jRadioButtonFornecedor) {
        this.jRadioButtonFornecedores = jRadioButtonFornecedor;
    }

    public JRadioButton getjRadioButtonVendedor() {
        return jRadioButtonVendedores;
    }

    public void setjRadioButtonVendedor(JRadioButton jRadioButtonVendedor) {
        this.jRadioButtonVendedores = jRadioButtonVendedor;
    }
    
    private void jRadioButtonVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVendedoresActionPerformed
        // TODO add your handling code here:
        controladoraPessoa.consultaPessoa(jTablePessoas,  buttonGroupTipo.getSelection().getMnemonic()); 
    }//GEN-LAST:event_jRadioButtonVendedoresActionPerformed

    private void jRadioButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClientesActionPerformed
        // TODO add your handling code here:
         controladoraPessoa.consultaPessoa(jTablePessoas, buttonGroupTipo.getSelection().getMnemonic());
    }//GEN-LAST:event_jRadioButtonClientesActionPerformed

    private void jRadioButtonFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFornecedoresActionPerformed
        // TODO add your handling code here:
         controladoraPessoa.consultaPessoa(jTablePessoas, buttonGroupTipo.getSelection().getMnemonic());
    }//GEN-LAST:event_jRadioButtonFornecedoresActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int linha = jTablePessoas.getSelectedRow();
        if ( linha >= 0) {
            pesSelecionado = (Pessoa) jTablePessoas.getValueAt(linha,0);
            try {
                controladoraPessoa.excluirPessoa(pesSelecionado, jTablePessoas);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERRO ao excluir PESSOA.");
                Logger.getLogger(TelaExibirPessoas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha.");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        controladoraPessoa.getPessoaSelecionada(this.getTela(), this, jTablePessoas, buttonGroupTipo.getSelection().getMnemonic());
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibirPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibirPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibirPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibirPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaExibirPessoas dialog;
                try {
                    dialog = new TelaExibirPessoas(new javax.swing.JFrame(), true);
               
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaExibirPessoas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JPanel jPanelExibirPessoas;
    private javax.swing.JPanel jPanelTabelaPessoas;
    private javax.swing.JPanel jPanelTipo;
    private javax.swing.JRadioButton jRadioButtonClientes;
    private javax.swing.JRadioButton jRadioButtonFornecedores;
    private javax.swing.JRadioButton jRadioButtonVendedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablePessoas;
    // End of variables declaration//GEN-END:variables
}
